//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingServerTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRoutingCalculator")]
    public interface IRoutingCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingCalculator/GetItinerary", ReplyAction="http://tempuri.org/IRoutingCalculator/GetItineraryResponse")]
        string GetItinerary(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingCalculator/GetItinerary", ReplyAction="http://tempuri.org/IRoutingCalculator/GetItineraryResponse")]
        System.Threading.Tasks.Task<string> GetItineraryAsync(string origin, string destination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoutingCalculatorChannel : RoutingServerTest.ServiceReference1.IRoutingCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingCalculatorClient : System.ServiceModel.ClientBase<RoutingServerTest.ServiceReference1.IRoutingCalculator>, RoutingServerTest.ServiceReference1.IRoutingCalculator {
        
        public RoutingCalculatorClient() {
        }
        
        public RoutingCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetItinerary(string origin, string destination) {
            return base.Channel.GetItinerary(origin, destination);
        }
        
        public System.Threading.Tasks.Task<string> GetItineraryAsync(string origin, string destination) {
            return base.Channel.GetItineraryAsync(origin, destination);
        }
    }
}
